# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 12:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='group',
            name='user',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='tag',
            new_name='tags',
        ),
        migrations.RenameField(
            model_name='waitinguser',
            old_name='user',
            new_name='users',
        ),
        migrations.AddField(
            model_name='activity',
            name='users',
            field=models.ManyToManyField(related_name='participants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activity',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
