# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitinguser',
            name='started_at',
            field=models.DateTimeField(null=True),
        ),
    ]
