# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 11:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waitinguser',
            name='users',
        ),
        migrations.AddField(
            model_name='waitinguser',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waitings', to=settings.AUTH_USER_MODEL),
        ),
    ]
