# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-20 16:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20170417_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
