GEOPOSITION_GOOGLE_MAPS_API_KEY = 'AIzaSyD48NmCV_kXSHmaGQSdEGojD7vkcRcNqME'

# Disqus
# https://django-disqus.readthedocs.io/en/latest/index.html
DISQUS_SECRET_KEY = 'gynqmLZtgK7aIaYuwHdFoLWjDerZFkWpfWac1zkFous8aK6Sz0RF5Nw8rWCu5GeQ'
DISQUS_PUBLIC_KEY = '52feWIkZMvNio7AVhezz8T28J552MHkeZL7w1YS6PtjWxRUbKkAADWGB70KXT1NC'
DISQUS_WEBSITE_SHORTNAME = 'meethub-1'